
name: Build My App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses : actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Flutter pub get
        uses: flutter pub get

      - name: Build release apk
        run : flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: /build/app/outputs/flutter-apk/app-release.apk