
name: Build My App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses : actions/checkout@v4
      - name: Set up JDK 17
        uses : actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Make gradlew executable
        run : chmod +x gradlew

      - name: Build release apk
        run : ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk